modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Markus1002/Autumnity/issues"
[[mods]]
modId="autumnity"
version="1.4.0"
displayName="Autumnity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autumnity"
credits="Markus1002, Artists: Markus1002, Farcr, Five and Snake"
authors="Markus1002"
description='''An autumn-themed mod with new biomes and useful snails.'''
[[dependencies.autumnity]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.57,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"
