modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/autumnity/issues"
[[mods]]
modId="autumnity"
version="1.1.1"
displayName="Autumnity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autumnity"
credits="Markus1002, Translators: mARRSSSSSS, H4Mm3r_"
authors="Markus1002"
description='''An autumn-themed mod with new biomes and friendly snails.'''
[[dependencies.autumnity]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
