modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/autumnity/issues"
[[mods]]
modId="autumnity"
version="1.0.0"
displayName="Autumnity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autumnity"
credits="Markus1002"
authors="Markus1002"
description='''Adds an autumn-themed biome with a new wood type and a new critter, which lives there.'''
[[dependencies.autumnity]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
