modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/autumnity/issues"
license = "https://github.com/team-abnormals/autumnity/blob/main/LICENSE.txt"

[[mods]]
    modId = "autumnity"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    displayName = "Autumnity"
    authors = "Team Abnormals"
    credits = "Markus1002, Farcr, Five, Echolite, and hatsondogs"
    description = '''
    An autumn-themed mod with new biomes and friendly snails.
    '''

[[dependencies.autumnity]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.autumnity]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.0.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.autumnity]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.1,)"
    ordering = "AFTER"
    side = "BOTH"